// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID             string         `json:"id"`
	ApiKeyHash     string         `json:"api_key_hash"`
	Name           string         `json:"name"`
	AllowedDomains string         `json:"allowed_domains"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      sql.NullTime   `json:"expires_at"`
	UsageCount     int64          `json:"usage_count"`
	LastUsedAt     sql.NullTime   `json:"last_used_at"`
	LastUsedIp     sql.NullString `json:"last_used_ip"`
	LastUsedID     sql.NullString `json:"last_used_id"`
}

type ApiUsage struct {
	ID             string         `json:"id"`
	ApiKeyID       string         `json:"api_key_id"`
	Timestamp      time.Time      `json:"timestamp"`
	StatusCode     string         `json:"status_code"`
	ResponseTimeMs sql.NullInt64  `json:"response_time_ms"`
	RequestIp      string         `json:"request_ip"`
	FromAddr       string         `json:"from_addr"`
	ToAddr         string         `json:"to_addr"`
	Subject        string         `json:"subject"`
	Status         string         `json:"status"`
	Webhook        sql.NullString `json:"webhook"`
}

type User struct {
	ID              string         `json:"id"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	LastPassword    sql.NullString `json:"last_password"`
	RequirePwChange bool           `json:"require_pw_change"`
	InvitedBy       sql.NullString `json:"invited_by"`
	AccountType     string         `json:"account_type"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}
