// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteApiKeyByCreatorId(ctx context.Context, createdBy string) error
	DeleteApiKeyById(ctx context.Context, id string) error
	DeleteUserByEmail(ctx context.Context, email string) error
	DeleteUserById(ctx context.Context, id string) error
	ForceUserChangePasswordByEmail(ctx context.Context, email string) error
	ForceUserChangePasswordById(ctx context.Context, id string) error
	GetAllUsers(ctx context.Context) ([]User, error)
	GetApiKeyByCreatorId(ctx context.Context, createdBy string) ([]ApiKey, error)
	GetApiKeyByIdAndCreatorId(ctx context.Context, arg GetApiKeyByIdAndCreatorIdParams) (ApiKey, error)
	GetApiKeyByKeyHash(ctx context.Context, apiKeyHash string) (ApiKey, error)
	GetApiKeyByNameAndCreatorId(ctx context.Context, arg GetApiKeyByNameAndCreatorIdParams) ([]ApiKey, error)
	GetApiKeyUsageByKeyIdAndUserId(ctx context.Context, arg GetApiKeyUsageByKeyIdAndUserIdParams) ([]ApiUsage, error)
	GetApiKeys(ctx context.Context) ([]ApiKey, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id string) (User, error)
	RefreshApiKey(ctx context.Context, arg RefreshApiKeyParams) error
	SaveApiKey(ctx context.Context, arg SaveApiKeyParams) (ApiKey, error)
	UpatePasswordByEmail(ctx context.Context, arg UpatePasswordByEmailParams) error
	UpdatePasswordById(ctx context.Context, arg UpdatePasswordByIdParams) error
}

var _ Querier = (*Queries)(nil)
